### ISSUE TITLE
Test card for testing purposes

### ISSUE THREAD

**Issue by EaranMaleasi** [EaranMaleasi/SIMDoku#3]
This is a test card to tes the GitHub integration of GloBoards. 
If this goes well, I'll be handling Issues with Glo. 

- [x] See if this works well with GitHub
- [x] Let other people look over it

**Comment by florian03-1** [comment]
Dies ist mal ein Testkommentar

**Comment by MichaHo** [comment]
Von mir auch ein Kommentar

**Comment by EaranMaleasi** [comment]
Danke @MichaHo & @flori2212

**Comment by EaranMaleasi** [comment]
As it is now, the projects are not synced with glow boards. While I probably will use GitKrakens Glow feature to add comments, the main issue management will happen within GitHub. 

If Glo at some point in time gets a project board sync feature, I will switch over to fully use Glo.
